- client/dist/styles.css
- client/src/components/App.jsx
- client/src/components/questions/Answer.jsx
- client/src/components/questions/AnswerList.jsx
- client/src/components/questions/Qsearch.jsx
- client/src/components/questions/Question.jsx
- client/src/components/questions/QuestionList.jsx
- client/src/components/questions/testing/sortAnswers.js
- client/src/components/questions/testing/sortAnswers.test.js
Question list sorter
Answer list sorter
Created test for answer list sorter
Tested and confirmed pass for answer list sorter with sample data
> implemented sorting functions for questions and answers

- client/src/components/questions/QuestionList.jsx
> fix for question sorter when no props passed

- auth copy.js
- package-lock.json
- server/index.js
> Server basic implementation

- client/src/components/App.jsx
- client/src/components/overview/Overview.jsx
- client/src/components/overview/RequestAPI.jsx
- client/src/components/overview/docs/overview-tasks.md
- client/src/components/overview/overview-styles.css
- client/src/components/shared/Stars.jsx
- client/src/components/shared/star-styles.css
Changed from left column and right column to top half and bottom half to better accommodate Expanded View implementation.
https://trello.com/c/994XPsFA
> Flex Box Containers for Overview re-designed

- client/dist/index.html
- client/dist/overview-styles.css
overview-styles.css, star-styles.css moved to client/dist/. Filepaths in index.html and overview-styles.css updated to reflect change.
*Ticket*
https://trello.com/c/o8y0Ilvz
> Filepaths update for Stylesheets

- client/dist/ratings-styles.css
- client/src/components/ratings/overallRating/OverallRating.jsx
- client/src/components/ratings/overallRating/productBreakdown/ProductBreakdown.jsx
Does not really change the review of the app @mutton808 @c4mino
> comment out some console logs, and update width of the ratings component

- server/index.js
Also removed some console logs.
Some are commented out, can recomment for debugging purposes.
@c4mino @yxxy666
> Added put handler to server

- client/dist/ratings-styles.css
- client/src/components/ratings/Ratings.jsx
- client/src/components/ratings/overallRating/OverallRating.jsx
- client/src/components/ratings/overallRating/ratingDist/RatingBar.jsx
- client/src/components/ratings/overallRating/ratingDist/RatingDist.jsx
- client/src/components/ratings/reviewList/ReviewList.jsx
- client/src/components/ratings/reviewList/SortReview.jsx
- client/src/components/ratings/reviewList/reviewBox/ReviewBox.jsx
- Make reviews sort by relevance, time and helpfulness
- Relevance is calculated as normalized time difference minus normalized helpfulness
- When click on a specific rating bar, show reviews of only that rating.
- Trello ticket with gif showing the change: https://trello.com/c/aGdhxYYy
@mutton808 @c4mino
> Worked on the sort and filter functions in the rating & reviews session

- client/dist/overview-styles.css
- client/src/components/overview/Overview.jsx
- client/src/components/overview/overview-components/Carousel.jsx
- client/src/components/overview/overview-components/NavigationArrows.jsx
##changeView
Changing views by expand/collapse button, or changing views by clicking main image from any of the three view states now behaves as expected.
d.
Magnify view WIP.
*Ticket*
https://trello.com/c/cG7Yw5L0
> Update logic for changeView function for onClick to change views

- client/dist/overview-styles.css
- client/src/components/overview/Overview.jsx
- client/src/components/overview/overview-components/Carousel.jsx
Clicking main image from expanded view Zooms image by 2.5x. Image moves in relation to user's cursor.
*bug: if user is scrolled down main page, centering of zoomed image will be moved by the amount of the scroll.*
**Ticket**
https://trello.com/c/cG7Yw5L0
> Zoomed View

- client/dist/ratings-styles.css
- client/src/components/ratings/Ratings.jsx
- client/src/components/ratings/reviewList/SortReview.jsx
- client/src/components/ratings/reviewList/reviewBox/ReviewEntry.jsx
- client/src/components/ratings/reviewList/reviewBox/reviewPhoto.jsx
- Showing " I recommend this product" line.
- Showing seller response if there is any.
- Limit review body to 250 characters, and button to expand/collapse to review full review body.
- Add thumbnail of review photos if there is any.
- When click on photo, open a modal with full-resolution photo showing.
- Trello ticket with gif attached: https://trello.com/c/FaThnbLf
@mutton808 @c4mino Feel free to take a look
> Add features to the individual rating tile component

- client/dist/questions-styles.css
- client/src/components/questions/AddAnswerModal.jsx
- client/src/components/questions/AddQuestionModal.jsx
- client/src/components/questions/Question.jsx
- client/src/components/questions/info.txt
- package-lock.json
- package.json
- server/index.js
Input Validation
Api post request
Todo:
Currently can only open window once
Photo upload section
> Add Answer Modal Functioning

- client/dist/questions-styles.css
- client/src/components/questions/AddAnswerModal.jsx
- client/src/components/questions/AddPhotosModal.jsx
- client/src/components/questions/AddQuestionModal.jsx
- client/src/components/questions/QnA.jsx
- client/src/components/questions/Question.jsx
- client/src/components/questions/QuestionList.jsx
- server/index.js
Add Photo Modal:
- preview thumbnails
- url input
- works with parent modal 
Todo:
- styling
- url validation
> add photo modal implemented functionality

- client/src/components/questions/AddPhotosModal.jsx
> Removed extra import statement that is not needed

- client/src/components/questions/AddQuestionModal.jsx
Should actually be fixed this time
> Removed other extra dependency

- client/dist/questions-styles.css
- client/src/components/questions/AnswerList.jsx
- client/src/components/questions/Question.jsx
- client/src/components/questions/QuestionList.jsx
- client/src/components/questions/info.txt
CSS and associated teaks for the qna module.
Font now matches other modules.
Styling more similar to other modules and visual design
Todo:
Modal styling
Helpful vote/reported styling
More tweaks overall
> Styling and more styling

- client/dist/index.html
- client/dist/overview-styles.css
**to use, add:**
font-weight: 700;
> added 700 font weight to roboto font

- client/dist/index.html
- client/dist/react-dom.development.js
- client/dist/react.development.js
- client/src/components/App.jsx
- client/src/components/overview/Overview.jsx
- client/src/components/questions/QnA.jsx
- client/src/components/questions/QuestionList.jsx
- client/src/components/ratings/Ratings.jsx
- client/src/components/ratings/overallRating/OverallRating.jsx
- client/src/components/ratings/reviewList/ReviewList.jsx
Shared api requests are now done in the app component and then passed down.
Testing shows no bugs at the moment but that doesn't mean there aren't any.
Lighthouse before
Lighthouse after
- Added react files to server to increase speed
- added styles.css to in page stylesheet instead
- removed react dev script resource
> Api refactor and performance increases

- client/dist/index.html
- client/dist/overview-styles.css
- client/dist/questions-styles.css
- client/dist/ratings-styles.css
- client/dist/related-styles.css
- client/dist/styles.css
- client/src/components/App.jsx
- client/src/components/questions/QnA.jsx
- client/src/components/ratings/Ratings.jsx
Added <div> container to Ratings component and QnA component. Additional styling for width, centering, color theme and button consistency.
> styling and centering, ratings and qna

- client/src/components/App.jsx
- client/src/components/questions/AddAnswerModal.jsx
- client/src/components/questions/AddPhotosModal.jsx
- client/src/components/questions/AddQuestionModal.jsx
- client/src/components/questions/Answer.jsx
- client/src/components/questions/AnswerList.jsx
- client/src/components/questions/QnA.jsx
- client/src/components/questions/Question.jsx
- client/src/components/questions/QuestionList.jsx
- client/src/components/shared/interactions.js
Interactions only need to be recorded for user interactable elements like buttons or links.
Please note this will use an api request for each interaction recorded
import interactions from '../shared/interactions.js';
interactions("elementName", "widgetName(ie module)");
interactions("closeAddQuestionModal", "questions");
Can either pass down as props or import in each component that needs it
> Interactions api, and questions module implementation

- client/dist/index.html
- client/dist/overview-styles.css
- client/dist/questions-styles.css
- client/dist/styles.css
- client/src/components/overview/overview-components/ProductDetails.jsx
Click "read all reviews" to scroll automatically to the reviews section.
*Ticket*
https://trello.com/c/H2ozpEzQ
> "read all reviews" link scrolls user to Reviews section

- client/dist/ratings-styles.css
- client/src/components/App.jsx
- client/src/components/ratings/Ratings.jsx
- client/src/components/ratings/overallRating/OverallRating.jsx
- client/src/components/ratings/overallRating/productBreakdown/CharacterRating.jsx
- client/src/components/ratings/reviewList/ReviewList.jsx
- client/src/components/ratings/reviewList/newReview/AddPhoto.jsx
- client/src/components/ratings/reviewList/newReview/CharacterRadio.jsx
- client/src/components/ratings/reviewList/newReview/NewReview.jsx
- client/src/components/ratings/reviewList/newReview/characteristics.js
- client/src/components/ratings/reviewList/reviewBox/ReviewPhoto.jsx
Product Breakdown:
Previous:
Current:
New Review Modal:
- Finished the function to add photo/remove photo
- Check for required fields before submit new review
- Upon submit, send POST request to API to store the review
Add photo:
Submit review:
Trello ticket: https://trello.com/c/DiJmpOV0
@mutton808 @c4mino Feel free to take a look!
> Finished the New Review Modal and Update Appearance of the Product Breakdown

- client/dist/questions-styles.css
- client/src/components/App.jsx
- client/src/components/questions/Question.jsx
Max size of 100vh for questions module.
Max size of 50vh for answer list.
Both scrollable.
Answer list scroll bar swapped to left side to not overlap with module scroll bar.
> scroll bars and styling

- client/dist/questions-styles.css
> Padding for scroll bars

- client/dist/ratings-styles.css
- client/src/components/ratings/reviewList/SearchReview.jsx
@mutton808 @c4mino Small update
> Added scroll bar; Added interaction report to the search review bar

- client/dist/questions-styles.css
Same functionality but scroll bars are hidden
> Hidden scroll bars
